
import { WorkItem } from './types';

export const WORK_TYPE_OPTIONS = [
  'PAKISTANI PP RENEWAL',
  'ID TYPE',
  'Lost PP Certificate',
  'Police Clearance',
  'Driving Licence',
  'Car Mulkiya',
  'Out Pass',
  'Cancel Visa',
  'Medical type',
  'Mohare est update',
  'withdraw absconding',
  'work permit',
  'labor cancel',
  'NUMBER UPDATE',
  'Issue visa',
];

export const INITIAL_STATUS_OPTIONS: string[] = [
  'UNDER PROCESSING',
  'Approved',
  'Rejected',
  'Waiting Delivery',
  'WAITING FOR FINGERPRINT',
  'PAID ONLY',
  'PENDING',
  'Deliverd',
];

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: '1',
    dateOfWork: '2025-09-29',
    workBy: 'AINUL',
    workOfType: 'PAKISTANI PP RENEWAL',
    status: 'UNDER PROCESSING',
    customerName: 'AHMED ULLAH',
    trackingNumber: 'L-P542670455',
    passportNumber: '',
    mobileWhatsappNumber: '971506059729',
    dayCount: 23,
    salesPrice: 150,
    advance: 50,
    due: 100,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '2',
    dateOfWork: '2025-09-02',
    workBy: 'AINUL',
    workOfType: 'Lost PP Certificate',
    status: 'UNDER PROCESSING',
    customerName: 'SIPON ALI',
    trackingNumber: 'L-P542670455',
    passportNumber: '',
    mobileWhatsappNumber: '971563960743',
    dayCount: 50,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '3',
    dateOfWork: '2025-09-13',
    workBy: 'AINUL',
    workOfType: 'Lost PP Certificate',
    status: 'UNDER PROCESSING',
    customerName: 'ISHAK ALI',
    trackingNumber: 'L-P542674602',
    passportNumber: '',
    mobileWhatsappNumber: '971557864954',
    dayCount: 39,
    salesPrice: 250,
    advance: 100,
    due: 150,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '4',
    dateOfWork: '2025-10-10',
    workBy: 'AINUL',
    workOfType: 'withdraw absconding',
    status: 'Rejected',
    customerName: 'saidul',
    trackingNumber: 'MB301010289AE',
    passportNumber: '',
    mobileWhatsappNumber: 'saidul',
    dayCount: 12,
    salesPrice: 1000,
    advance: 0,
    due: 1000,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '5',
    dateOfWork: '2025-10-15',
    workBy: '',
    workOfType: 'withdraw absconding',
    status: 'UNDER PROCESSING',
    customerName: 'JUWEL MIAH',
    trackingNumber: 'MB301291844AE',
    passportNumber: '',
    mobileWhatsappNumber: '971564561696',
    dayCount: 7,
    salesPrice: 800,
    advance: 500,
    due: 300,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '6',
    dateOfWork: '2025-10-17',
    workBy: 'MONIR',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'RABIUL ISLAM SAHIDUL ISLAM',
    trackingNumber: 'L-P542688282',
    passportNumber: '',
    mobileWhatsappNumber: '971547297832',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '7',
    dateOfWork: '2025-10-17',
    workBy: 'AINUL',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'MD HALIMUR RAHMAN',
    trackingNumber: 'L-P542688318',
    passportNumber: '',
    mobileWhatsappNumber: '971507859725',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '8',
    dateOfWork: '2025-10-17',
    workBy: 'MONIR',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'KOWSOR ANSWARI SAMIR UDDIN',
    trackingNumber: 'L-P542688357',
    passportNumber: '',
    mobileWhatsappNumber: '971543103720',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: true,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '9',
    dateOfWork: '2025-10-20',
    workBy: 'MONIR',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'EMON BHUIYAN',
    trackingNumber: 'L-P542688943',
    passportNumber: '',
    mobileWhatsappNumber: '971545915017',
    dayCount: 2,
    salesPrice: 200,
    advance: 150,
    due: 50,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '10',
    dateOfWork: '2025-10-20',
    workBy: 'AINUL',
    workOfType: 'ID TYPE',
    status: 'Waiting Delivery',
    customerName: 'Mohammad Maraj',
    trackingNumber: '0102611132282025537737095',
    passportNumber: '',
    mobileWhatsappNumber: '971568484131',
    dayCount: 2,
    salesPrice: 350,
    advance: 350,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
];

const allWorkBy = INITIAL_WORK_ITEMS.map(item => item.workBy).filter(Boolean);
export const INITIAL_WORK_BY_OPTIONS = [...new Set(allWorkBy), 'alam bhi'];