
import { WorkItem, WorkTypeConfig } from './types';

export const INITIAL_WORK_TYPE_CONFIGS: WorkTypeConfig[] = [
  { name: 'Pakistani PP Renewal' },
  { name: 'ID Type' },
  { name: 'Lost PP Certificate', trackingUrl: 'https://www.dubaipolice.gov.ae/wps/portal/home/hidden/verifyidentity' },
  { name: 'Police Clearance', trackingUrl: 'https://www.dubaipolice.gov.ae/wps/portal/home/hidden/verifyidentity' },
  { name: 'Driving Licence' },
  { name: 'Car Mulkiya' },
  { name: 'Out Pass' },
  { name: 'Cancel Visa' },
  { name: 'Medical Type' },
  { name: 'Mohare Est Update', trackingUrl: 'https://inquiry.mohre.gov.ae' },
  { name: 'Withdraw Absconding', trackingUrl: 'https://inquiry.mohre.gov.ae' },
  { name: 'Work Permit', trackingUrl: 'https://inquiry.mohre.gov.ae' },
  { name: 'Labor Cancel', trackingUrl: 'https://inquiry.mohre.gov.ae' },
  { name: 'Number Update' },
  { name: 'Issue Visa' },
];

export const INITIAL_STATUS_OPTIONS: string[] = [
  'Under Processing',
  'Approved',
  'Rejected',
  'Waiting Delivery',
  'Waiting For Fingerprint',
  'Paid Only',
  'Pending',
  'Deliverd',
];

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: '1',
    dateOfWork: '2025-09-29',
    workBy: 'Ainul',
    workOfType: 'Pakistani PP Renewal',
    status: 'Under Processing',
    customerName: 'Ahmed Ullah',
    trackingNumber: 'L-P542670455',
    passportNumber: '',
    mobileWhatsappNumber: '971506059729',
    dayCount: 23,
    salesPrice: 150,
    advance: 50,
    due: 100,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '2',
    dateOfWork: '2025-09-02',
    workBy: 'Ainul',
    workOfType: 'Lost PP Certificate',
    status: 'Under Processing',
    customerName: 'Sipon Ali',
    trackingNumber: 'L-P542670455',
    passportNumber: '',
    mobileWhatsappNumber: '971563960743',
    dayCount: 50,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '3',
    dateOfWork: '2025-09-13',
    workBy: 'Ainul',
    workOfType: 'Lost PP Certificate',
    status: 'Under Processing',
    customerName: 'Ishak Ali',
    trackingNumber: 'L-P542674602',
    passportNumber: '',
    mobileWhatsappNumber: '971557864954',
    dayCount: 39,
    salesPrice: 250,
    advance: 100,
    due: 150,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '4',
    dateOfWork: '2025-10-10',
    workBy: 'Ainul',
    workOfType: 'Withdraw Absconding',
    status: 'Rejected',
    customerName: 'Saidul',
    trackingNumber: 'MB301010289AE',
    passportNumber: '',
    mobileWhatsappNumber: 'saidul',
    dayCount: 12,
    salesPrice: 1000,
    advance: 0,
    due: 1000,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '5',
    dateOfWork: '2025-10-15',
    workBy: '',
    workOfType: 'Withdraw Absconding',
    status: 'Under Processing',
    customerName: 'Juwel Miah',
    trackingNumber: 'MB301291844AE',
    passportNumber: '',
    mobileWhatsappNumber: '971564561696',
    dayCount: 7,
    salesPrice: 800,
    advance: 500,
    due: 300,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '6',
    dateOfWork: '2025-10-17',
    workBy: 'Monir',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'Rabiul Islam Sahidul Islam',
    trackingNumber: 'L-P542688282',
    passportNumber: '',
    mobileWhatsappNumber: '971547297832',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '7',
    dateOfWork: '2025-10-17',
    workBy: 'Ainul',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'MD Halimur Rahman',
    trackingNumber: 'L-P542688318',
    passportNumber: '',
    mobileWhatsappNumber: '971507859725',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '8',
    dateOfWork: '2025-10-17',
    workBy: 'Monir',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'Kowsor Answari Samir Uddin',
    trackingNumber: 'L-P542688357',
    passportNumber: '',
    mobileWhatsappNumber: '971543103720',
    dayCount: 5,
    salesPrice: 200,
    advance: 200,
    due: 0,
    isArchived: true,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '9',
    dateOfWork: '2025-10-20',
    workBy: 'Monir',
    workOfType: 'Lost PP Certificate',
    status: 'Approved',
    customerName: 'Emon Bhuiyan',
    trackingNumber: 'L-P542688943',
    passportNumber: '',
    mobileWhatsappNumber: '971545915017',
    dayCount: 2,
    salesPrice: 200,
    advance: 150,
    due: 50,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
  {
    id: '10',
    dateOfWork: '2025-10-20',
    workBy: 'Ainul',
    workOfType: 'ID Type',
    status: 'Waiting Delivery',
    customerName: 'Mohammad Maraj',
    trackingNumber: '0102611132282025537737095',
    passportNumber: '',
    mobileWhatsappNumber: '971568484131',
    dayCount: 2,
    salesPrice: 350,
    advance: 350,
    due: 0,
    isArchived: false,
    isTrashed: false,
    customerCalled: false,
  },
];

const allWorkBy = INITIAL_WORK_ITEMS.map(item => item.workBy).filter(Boolean);
export const INITIAL_WORK_BY_OPTIONS = [...new Set(allWorkBy), 'Alam Bhi'];